[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "c3c087202f74d836f785c1914d643794db60a89b"
os = "macos"

    [[PATHlib.download]]
    sha256 = "88e6c76ecde10b6002f93df9099ee8637f472e4a29794150286a2b9f7c0398d4"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.x86_64-apple-darwin14.tar.gz"
[[PATHlib]]
arch = "i686"
git-tree-sha1 = "0fc1a32e215f5f8d37a9f850a000557bb70d1c9e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PATHlib.download]]
    sha256 = "6645148f856eb9c338b59f2a65559e90a12434f5bf723f26600d83856cf38a28"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.i686-linux-gnu-libgfortran3.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "27986e6f0845fd368b6db1c927390fc06c41747b"
libgfortran_version = "3.0.0"
os = "windows"

    [[PATHlib.download]]
    sha256 = "181915c6212782f80a2ac9ba0c07e86041a8af03f01829848c1bbe17f59f6e6f"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "939765f0dfd8f6cd576ef7b782350c745380969b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PATHlib.download]]
    sha256 = "3ec166089890804c9a0abfabe1dc45af92b5a3890df92e57b9972657cb94709b"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "7841ac3b2231e880c38ca998b72f50da3aa8bbe9"
libgfortran_version = "3.0.0"
os = "macos"

    [[PATHlib.download]]
    sha256 = "caa8deafb516ebaf0c4a58c368c2511177a7014e83208ee77ab825bb6f52d74d"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[PATHlib]]
arch = "i686"
git-tree-sha1 = "65bafcc26eec1f28ee1d7baaaf81dccc1f962b5b"
libgfortran_version = "4.0.0"
os = "windows"

    [[PATHlib.download]]
    sha256 = "1dd3970f02aca275460c8b47c2e5285846d5d67f49cd98f34b0f9ef860221a68"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.i686-w64-mingw32-libgfortran4.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "045e41060338ee0d6865e42dcb0bfd5f86cc3213"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PATHlib.download]]
    sha256 = "50e0defc0f8261605c5b24ecc4c538e0526895e2bfb6a8c2a2612cce9d70073b"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.x86_64-linux-gnu-libgfortran3.tar.gz"
[[PATHlib]]
arch = "i686"
git-tree-sha1 = "2a46ba358577af913bb315cfd180264f509607e1"
libgfortran_version = "5.0.0"
os = "windows"

    [[PATHlib.download]]
    sha256 = "348b23bcc191f07442e235c2ca7e8f63a9353760bb88d0e420ccd3ac72dcf902"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.i686-w64-mingw32-libgfortran5.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "f38a0d04fb4286a9ad08fde1407c6f5c3764ca6c"
libgfortran_version = "5.0.0"
os = "windows"

    [[PATHlib.download]]
    sha256 = "a37032770e69907bbe0f9461e122acefef1c51f276d74d4c65cfdbb7d09173a1"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "950d156bd6e2612396a96bd6dd727e8c4f2f7ea8"
libgfortran_version = "5.0.0"
os = "macos"

    [[PATHlib.download]]
    sha256 = "e1f3d3daac749c6c286bd7c94eb4073fc9292ba2cb84ccf8308a2becb676bd31"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "bb6727dec24cd7125470c73705ff57b5ba8fa3b8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PATHlib.download]]
    sha256 = "7828fd694e2ec45388898b690d0332ee902ede62e4ab5431eee993879884b0f7"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "e52d0301936399196acd4276879fb5cdb5008dca"
libgfortran_version = "4.0.0"
os = "macos"

    [[PATHlib.download]]
    sha256 = "bdf362d18e4fdc1f6d6b307c90aa685c366f722158b1741c3833c9ba65951c9b"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[PATHlib]]
arch = "i686"
git-tree-sha1 = "ebc5499e102371b177f0d976b4e9097d66918114"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PATHlib.download]]
    sha256 = "53df60673ebfba8e0b28d1ad229162e3b88bba33cd3760f5f86579035034dc4f"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.i686-linux-gnu-libgfortran5.tar.gz"
[[PATHlib]]
arch = "i686"
git-tree-sha1 = "e7eb81c958a16e20deb079a592c74cd0049ab867"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PATHlib.download]]
    sha256 = "49be6cd6b7de48663ea7d9d2803155819ac3ee5e8944d0d43c7dcdfbfd01ec8c"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.i686-linux-gnu-libgfortran4.tar.gz"
[[PATHlib]]
arch = "x86_64"
git-tree-sha1 = "b0de24115a4dd4b196da89cb115b6957b80887cc"
libgfortran_version = "4.0.0"
os = "windows"

    [[PATHlib.download]]
    sha256 = "903d844d6c7cf50cce6bceaf9886b1ac8694d6d80f16c181b6275cc33986f43d"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PATHlib]]
arch = "i686"
git-tree-sha1 = "81cfccfadc8072c5fe017bf958e011413e0a8062"
libgfortran_version = "3.0.0"
os = "windows"

    [[PATHlib.download]]
    sha256 = "5c1cc797e5fc7aa324aa1cebf9ec7bf0b7d93a7d1ad3bef1d5cb72a7ea38f52a"
    url = "https://github.com/JuliaBinaryWrappers/PATHlib_jll.jl/releases/download/PATHlib-v4.7.3+0/PATHlib.v4.7.3.i686-w64-mingw32-libgfortran3.tar.gz"
